@base = http://localhost/SIPAN
@api = http://localhost/SIPAN/api

POST {{api}}/ingresar
Content-Type: application/json

{
  "correo": "franyeradriansanchez@gmail.com",
  "clave": "Fran.0610"
}

###
POST {{api}}/registrarse
Content-Type: application/json

{
  "clave": "Fran.0610",
  "primer_nombre": "Franyer",
  "primer_apellido": "Sánchez",
  "correo": "franyeradriansanchez@gmail.com"
}

###
GET {{api}}/productos
